<a href="https://colab.research.google.com/github/trisskmasarahh/Machine-Learning_Ganjil_2025/blob/main/Praktikum_1_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PRAKTIKUM 1

In [16]:
#Langkah:

#Buat dataset sederhana (XOR).
#Inisialisasi bobot dan bias.
#Implementasikan forward pass.
#Hitung error dan lakukan backpropagation.
#Update bobot menggunakan gradient descent.

import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 2
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Output akhir
print("Prediksi:")
print(a2)

Epoch 0, Loss: 0.26982240673410274
Epoch 1000, Loss: 0.24956199103011312
Epoch 2000, Loss: 0.23381478073581946
Epoch 3000, Loss: 0.16860630285887235
Epoch 4000, Loss: 0.06575747350298303
Epoch 5000, Loss: 0.020225053567813383
Epoch 6000, Loss: 0.010093171321889773
Epoch 7000, Loss: 0.0064177580716371346
Epoch 8000, Loss: 0.004616079042232019
Epoch 9000, Loss: 0.003569522847902657
Prediksi:
[[0.04612863]
 [0.9487803 ]
 [0.94887809]
 [0.0648922 ]]


## Ubah jumlah neuron hidden layer menjadi 3.

In [17]:
#Tugas 1:

#Ubah jumlah neuron hidden layer menjadi 3.
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 3  # diganti dari 2 → 3 neuron
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Aktivasi sigmoid
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

loss_history_3 = []

# Training
for epoch in range(10000):
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    error = y - a2

    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        loss_history_3.append(loss)
        print(f"[Hidden 3] Epoch {epoch}, Loss: {loss}")

print("\nPrediksi (hidden=3):")
print(a2.round(3))


[Hidden 3] Epoch 0, Loss: 0.2542481957251896
[Hidden 3] Epoch 1000, Loss: 0.25030913373915975
[Hidden 3] Epoch 2000, Loss: 0.250075621030659
[Hidden 3] Epoch 3000, Loss: 0.25000948248451094
[Hidden 3] Epoch 4000, Loss: 0.24995747261221457
[Hidden 3] Epoch 5000, Loss: 0.24986871625922982
[Hidden 3] Epoch 6000, Loss: 0.2496137935926775
[Hidden 3] Epoch 7000, Loss: 0.24831231699974896
[Hidden 3] Epoch 8000, Loss: 0.2349810405742057
[Hidden 3] Epoch 9000, Loss: 0.15184931217075504

Prediksi (hidden=3):
[[0.193]
 [0.852]
 [0.815]
 [0.164]]


# Bandingkan hasil loss dengan konfigurasi awal.

Secara keseluruhan, konfigurasi awal terbukti lebih superior dibandingkan konfigurasi dengan hidden layer 3. Konfigurasi awal mampu mencapai konvergensi yang lebih cepat dan menghasilkan nilai loss akhir yang jauh lebih kecil (0.003 berbanding 0.151). Hal ini menunjukkan bahwa arsitektur awal lebih mampu memetakan karakteristik data input dengan presisi tinggi tanpa mengalami hambatan belajar (stagnansi) seperti yang terjadi pada percobaan kedua.

# Tambahkan fungsi aktivasi ReLU dan bandingkan hasil.

In [18]:
#Tambahkan fungsi aktivasi ReLU dan bandingkan hasil.
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 3
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Aktivasi ReLU & Sigmoid
def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return np.where(x > 0, 1, 0)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

loss_history_relu = []

# Training
for epoch in range(10000):
    z1 = np.dot(X, W1) + b1
    a1 = relu(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    error = y - a2

    # Backprop
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * relu_derivative(z1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        loss_history_relu.append(loss)
        print(f"[ReLU] Epoch {epoch}, Loss: {loss}")

print("\nPrediksi (ReLU):")
print(a2.round(3))


[ReLU] Epoch 0, Loss: 0.2800749885219016
[ReLU] Epoch 1000, Loss: 0.25
[ReLU] Epoch 2000, Loss: 0.25
[ReLU] Epoch 3000, Loss: 0.25
[ReLU] Epoch 4000, Loss: 0.25
[ReLU] Epoch 5000, Loss: 0.25
[ReLU] Epoch 6000, Loss: 0.25
[ReLU] Epoch 7000, Loss: 0.25
[ReLU] Epoch 8000, Loss: 0.25
[ReLU] Epoch 9000, Loss: 0.25

Prediksi (ReLU):
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
